syntax = "proto3";

package ceremony;

import "authenticator/assertion/response.proto";
import "authenticator/attachment.proto";
import "public_key_credential/type.proto";
import "webauthn/credential.proto";
import "webauthn/extensions.proto";

message Assertion {
  webauthn.Credential credential = 1;
  public_key_credential.Type type = 2;
  authenticator.Attachment authenticator_attachment = 3;
  webauthn.ResponseExtensions client_extension_results = 4;
  authenticator.assertion.Response response = 5;
}
