syntax = "proto3";

package public_key_credential;

import "public_key_credential/descriptor.proto";
import "requirement/user_verification.proto";
import "webauthn/challenge.proto";
import "webauthn/extensions.proto";
import "webauthn/relying_party.proto";

message RequestOptions {
  webauthn.Challenge challenge = 1;
  uint32 timeout = 2;
  webauthn.RpId rp_id = 3;
  repeated Descriptor allow_credentials = 4;
  requirement.UserVerification user_verification = 5;
  repeated string hints = 6;
  webauthn.RequestExtensions extensions = 7;
}
